---
ignore:
  - .env
  - .venv
  - .vscode
rule_settings:
  enable:
    - default
    - gpsg
  disable:
    - dont-import-test-modules
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: "3.12"
clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false