site_name: scott_tracy
theme:
  name: readthedocs

nav:
  - Home: index.md

plugins:
  - mermaid2:
      javascript: https://unpkg.com/mermaid/dist/mermaid.min.js
      arguments:
        startOnLoad: true